"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.postRoutes = void 0;
const express_1 = __importDefault(require("express"));
const user_getPosts_controller_1 = require("../controllers/user.getPosts.controller");
const user_newPost_controller_1 = require("../controllers/user.newPost.controller");
const user_likePost_controller_1 = require("../controllers/user.likePost.controller");
const user_comment_controller_1 = require("../controllers/user.comment.controller");
const multer_middleware_1 = require("../middleware/multer.middleware");
const auth_middleware_1 = require("../middleware/auth.middleware");
const { getUserPosts, getFriendsPosts, getPost, getFeedPosts } = new user_getPosts_controller_1.GetUserPostsController();
const { likeComment, comment, getComments } = new user_comment_controller_1.CommentController();
const { likePost, unlikePost } = new user_likePost_controller_1.PostLikeController();
const { userNewPost } = new user_newPost_controller_1.UserNewPostController();
const { memoryStorage } = new multer_middleware_1.MulterMiddleware();
const { verifyJwt } = new auth_middleware_1.JwtMiddleware();
const router = express_1.default.Router();
exports.postRoutes = router;
router.use(verifyJwt);
router.post('/', getUserPosts);
router.post('/feed', getFeedPosts);
router.post('/like-post', likePost);
router.post('/unlike-post', unlikePost);
router.post('/like-comment', likeComment);
router.post('/unlike-comment', unlikePost);
router.post('/friends-posts', getFriendsPosts);
router.post('/post', memoryStorage, userNewPost);
router.post('/new-comment', memoryStorage, comment);
router.post('/comments', memoryStorage, getComments);
router.get('/:id', getPost);
