User
- run: echo "GitHub Workspace: $GITHUB_WORKSPACE"
- run: ls -la $GITHUB_WORKSPACE

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3  # This action checks out your repository into the workspace
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Navigate to the backend directory
      run: cd backend  # Assuming the backend directory is at the root level of your repository
    - run: npm ci
    - run: |
        touch .env
        echo "{{ secrets.PROD_ENV_FILE }}" > .env
